package rules;
dialect  "mvel"

import com.sw.projekat.model.AutomobilQuery
import com.sw.projekat.model.Automobil
import com.sw.projekat.model.Osoba
import com.sw.projekat.model.User
import com.sw.projekat.model.enums.*
import com.sw.projekat.model.DodatneKarakteristike
import java.util.ArrayList

global AutomobilQuery q

rule "Porodicni automobil"
    agenda-group "based_on_car_and_person"
    salience 20
    lock-on-active true
    when
        $osoba:Osoba(getGodiste()==Godiste.SREDNJE_GODINE,getBrojClanovaPorodice()==BrojClanovaPorodice.VISECLANA_PORODICA)
        $automobil:Automobil(getDodatneKarakteristike().isKaroserijaPorodicni()==true)
    then
        System.out.println("Porodicni automobil(" + $automobil.getNaziv()+")");
        $automobil.getDodatneKarakteristike().setPorodicni(true);
        $automobil.addToScore(5);
        update($automobil);
end
rule "Muski automobil"
    agenda-group "based_on_car_and_person"
    salience 17
    lock-on-active true
    when
        $osoba:Osoba(getPol()==Pol.M)
        $automobil:Automobil(getDodatneKarakteristike().isMuskaBoja()==true)
    then
        System.out.println("Muski automobil(" + $automobil.getNaziv()+")");
        $automobil.addToScore(5);
        update($automobil);
end
rule "Zenski automobil"
    agenda-group "based_on_car_and_person"
    salience 18
    lock-on-active true
    when
        $osoba:Osoba(getPol()==Pol.Z)
        $automobil:Automobil(getDodatneKarakteristike().isZenskaBoja()==true)
    then
        System.out.println("Zenski automobil(" + $automobil.getNaziv()+")");
        $automobil.addToScore(5);
        update($automobil);
end
rule "Automobil za posao"
    agenda-group "based_on_car_and_person"
    salience 19
    lock-on-active true
    when
        $osoba:Osoba(isZaposlenost(),MestoPrebivalista.GRAD!=getMestoPrebivalista())
        $automobil:Automobil(getDodatneKarakteristike().isKaroserijaPorodicni()==true ||
        getDodatneKarakteristike().isKaroserijaDzipovi()==true)
    then
        System.out.println("Automobil za posao(" + $automobil.getNaziv()+")");
        $automobil.addToScore(5);
        update($automobil);
end
rule "Momacki auto"
    agenda-group "based_on_car_and_person"
    salience 19
    lock-on-active true
    when
        $osoba:Osoba(Pol.M==getPol(),getGodiste()==Godiste.MLADA_OSOBA)
        $automobil:Automobil(getDodatneKarakteristike().isKaroserijaSportskiLjetni()==true)
    then
        System.out.println("Momacki auto(" + $automobil.getNaziv()+")");
        $automobil.getDodatneKarakteristike().setMomacki(true);
        $automobil.addToScore(5);
        update($automobil);
end
rule "Automobil za nezaposlene"
    agenda-group "based_on_car_and_person"
    salience 19
    lock-on-active true
    when
        $osoba:Osoba(isZaposlenost()==false)
        $automobil:Automobil(getDodatneKarakteristike().isJeftin()==true)
    then
        System.out.println("Automobil za nezaposlene(" + $automobil.getNaziv()+")");
        $automobil.addToScore(5);
        update($automobil);
end
rule "Eko auto"
    agenda-group "based_on_car_and_person"
    salience 19
    lock-on-active true
    when
        $osoba:Osoba(MestoPrebivalista.GRAD==getMestoPrebivalista())
        $automobil:Automobil(getDodatneKarakteristike().isEkoloski()==true)
    then
        System.out.println("Eko auto(" + $automobil.getNaziv()+")");
        $automobil.addToScore(5);
        update($automobil);
end
