package rules;
dialect  "mvel"

import com.sw.projekat.model.AutomobilQuery
import com.sw.projekat.model.Automobil
import com.sw.projekat.model.enums.*
import java.util.ArrayList

global AutomobilQuery q
global ArrayList<Automobil> topCars;

rule "Tacna marka automobila"
    agenda-group "based_on_car"
    when
        $automobil:Automobil(getMarka()==q.getMarka())
    then
        System.out.println("Tacna marka automobila(" + $automobil.getId()+")");
        modify($automobil){addToScore(20)}
end
rule "Tacna karoserija automobila"
    agenda-group "based_on_car"
    when
        $automobil:Automobil(getKaroserija()==q.getKaroserija())
    then
        System.out.println("Tacna karoserija automobila(" + $automobil.getId()+")");
        modify($automobil){addToScore(20)}
end
rule "Slicna karoserija automobila - dzipovi "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getKaroserija()!=q.getKaroserija()),
        (getKaroserija()==Karoserija.DZIP || getKaroserija()==Karoserija.PICKUP))
    then
        System.out.println("Slicna karoserija automobila - dzipovi(" + $automobil.getId()+")");
        modify($automobil){addToScore(10)}
end
rule "Slicna karoserija automobila - porodicni "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getKaroserija()!=q.getKaroserija()),
        (getKaroserija()==Karoserija.LIMUZINA || getKaroserija()==Karoserija.HECBEK || getKaroserija()==Karoserija.KARAVAN || getKaroserija()==Karoserija.MINIVAN))
    then
        System.out.println("Slicna karoserija automobila - porodicni(" + $automobil.getId()+")");
        modify($automobil){addToScore(10)}
end
rule "Slicna karoserija automobila - sportski/ljetni "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getKaroserija()!=q.getKaroserija()),
        (getKaroserija()==Karoserija.KABRIOLET || getKaroserija()==Karoserija.KUPE))
    then
        System.out.println("Slicna karoserija automobila - sportski/ljetni(" + $automobil.getId()+")");
        modify($automobil){addToScore(10)}
end
rule "Cena je do 50% manja od unesene okvirne cene "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getCena()<=q.getCena()),
        (getCena()>=q.getCena()*0.5))
    then
        System.out.println("Cena je do 50% manja od unesene okvirne cene(" + $automobil.getId()+")");
        modify($automobil){addToScore(20)}
end
rule "Cena je do 10% veca od unesene okvirne cene "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getCena()>q.getCena()),
        (getCena()<=q.getCena()*1.1))
    then
        System.out.println("Cena je do 10% veca od unesene okvirne cene(" + $automobil.getId()+")");
        modify($automobil){addToScore(10)}
end
rule "Cena je do 50% veca od unesene okvirne cene "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getCena()>q.getCena()*1.1),
        (getCena()<=q.getCena()*1.5))
    then
        System.out.println("Cena je do 50% veca od unesene okvirne cene(" + $automobil.getId()+")");
        modify($automobil){addToScore(5)}
end
rule "Godište automobila je u rangu ± 5 "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getGodiste()>=q.getGodiste()-5),
        (getGodiste()<=q.getGodiste()+5))
    then
        System.out.println("Godište automobila je u rangu ± 5 (" + $automobil.getId()+")");
        modify($automobil){addToScore(20)};
end
rule "Godište automobila je u rangu ± 10 "
    agenda-group "based_on_car"
    when
        $automobil:Automobil(((getGodiste()>=q.getGodiste()-10) &&
         (getGodiste()<q.getGodiste()-5)) ||
        ((getGodiste()<=q.getGodiste()+10)&&
        (getGodiste()>q.getGodiste()+5)))
    then
        System.out.println("Godište automobila je u rangu ± 10 (" + $automobil.getId()+")");
        modify($automobil){addToScore(10)}
end
rule "Tacno gorivo automobila"
    agenda-group "based_on_car"
    when
        $automobil:Automobil(getGorivo()==q.getGorivo())
    then
        System.out.println("Tacno gorivo automobila(" + $automobil.getId()+")");
        modify($automobil){addToScore(10)}
end
rule "Slicna grupa goriva automobila - benzinac "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getGorivo()!=q.getGorivo()),
        (getGorivo()==Gorivo.BENZIN_GAS || getGorivo()==Gorivo.BENZIN || getGorivo()==Gorivo.BENZIN_METAN))
    then
        System.out.println("Slicna grupa goriva automobila - benzinac(" + $automobil.getId()+")");
        modify($automobil){addToScore(5)}
end
rule "Slicna grupa goriva automobila - ekoloski "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getGorivo()!=q.getGorivo()),
        (getGorivo()==Gorivo.ELEKTRICNI_POGON || getGorivo()==Gorivo.HIBRIDNI_POGON))
    then
        System.out.println("Slicna grupa goriva automobila - ekoloski(" + $automobil.getId()+")");
        modify($automobil){addToScore(5)}
end
rule "Klima u automobilu"
    agenda-group "based_on_car"
    when
        $automobil:Automobil(isKlima()==true,q.isKlima()==true)
    then
        System.out.println("Klima u automobilu(" + $automobil.getId()+")");
        modify($automobil){addToScore(5)}
end
rule "Kubikaza automobila je u rangu ± 10 "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getKubikaza()>=q.getKubikaza()-10),
        (getKubikaza()<=q.getKubikaza()+10))
    then
        System.out.println("Kubikaza automobila je u rangu ± 10 (" + $automobil.getId()+")");
        modify($automobil){addToScore(20)}
end
rule "Kubikaza automobila je u rangu ± 20 "
    agenda-group "based_on_car"
    when
        $automobil:Automobil(((getKubikaza()>=q.getKubikaza()-20) &&
        (getKubikaza()<q.getKubikaza()-10)) ||
        ((getKubikaza()<=q.getKubikaza()+20) &&
        (getKubikaza()>q.getKubikaza()+10)))
    then
        System.out.println("Kubikaza automobila je u rangu ± 20 (" + $automobil.getId()+")");
        modify($automobil){addToScore(10)}
end
rule "Kubikaza automobila je u rangu ± 40 "
    agenda-group "based_on_car"
    when
        $automobil:Automobil(((getKubikaza()>=q.getKubikaza()-40) &&
        (getKubikaza()<q.getKubikaza()-20)) ||
        ((getKubikaza()<=q.getKubikaza()+40) &&
        (getKubikaza()>q.getKubikaza()+20)))
    then
        System.out.println("Kubikaza automobila je u rangu ± 40 (" + $automobil.getId()+")");
        modify($automobil){addToScore(5)}
end
rule "Tacna boja automobila"
    agenda-group "based_on_car"
    when
        $automobil:Automobil(q.getBoja() == getBoja())
    then
        System.out.println("Tacna boja automobila(" + $automobil.getId()+")");
        modify($automobil){addToScore(10)}
end
rule "Slicna grupa boje automobila - zenska "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getBoja()!=q.getBoja()),
        (getBoja()==Boja.NARANDZASTA  || getBoja()==Boja.CRVENA
         || getBoja()==Boja.LJUBICASTA))
    then
        System.out.println("Slicna grupa boje automobila - zenska(" + $automobil.getId()+")");
        modify($automobil){getDodatneKarakteristike().setZenskaBoja(true)}
        modify($automobil){addToScore(5)}
end
rule "Slicna grupa boje automobila - muska "
    agenda-group "based_on_car"
    when
        $automobil:Automobil((getBoja()!=q.getBoja()),
        (getBoja()==Boja.CRNA || getBoja()==Boja.BRAON
         || getBoja()==Boja.SIVA))
    then
        System.out.println("Slicna grupa boje automobila - muska(" + $automobil.getId()+")");
        modify($automobil){getDodatneKarakteristike().setMuskaBoja(true)}
        modify($automobil){addToScore(5)}
end