 export enum Boja {
    BELA="BELA",
    CRNA="CRNA",
    NARANDZASTA="NARANDZASTA",
    LJUBICASTA="LJUBICASTA",
    ZUTA="ZUTA",
    CRVENA="CRVENA",
    ZLATNA="ZLATNA",
    SREBRNA="SREBRNA",
    SIVA="SIVA",
    ZELENA="ZELENA",
    PLAVA="PLAVA",
    BRAON="BRAON"
}