 export enum Gorivo {
    BENZIN="BENZIN",
    DIZEL="DIZEL",
    BENZIN_GAS="BENZIN_GAS",
    BENZIN_METAN="BENZIN_METAN",
    ELEKTRICNI_POGON="ELEKTRICNI_POGON",
    HIBRIDNI_POGON="HIBRIDNI_POGON"
}